language: node_js
node_js: stable

cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install


# before_script:
#  - npm install -g hexo-cli

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "simayubo"
  - git config user.email "simayubo@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/simayubo/somsan.git
